[2022-12-08T03:30:58.147+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:30:49.778249+00:00 [queued]>
[2022-12-08T03:30:58.167+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:30:49.778249+00:00 [queued]>
[2022-12-08T03:30:58.167+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T03:30:58.167+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-08T03:30:58.168+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T03:30:58.201+0000] {taskinstance.py:1304} INFO - Executing <Task(BigQueryCreateExternalTableOperator): wait_in_seller_line_create_external_table> on 2022-12-08 03:30:49.778249+00:00
[2022-12-08T03:30:58.211+0000] {standard_task_runner.py:55} INFO - Started process 157 to run task
[2022-12-08T03:30:58.218+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'streamify_dag', 'wait_in_seller_line_create_external_table', 'manual__2022-12-08T03:30:49.778249+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ticketsim.py', '--cfg-path', '/tmp/tmpdc4x09op']
[2022-12-08T03:30:58.223+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask wait_in_seller_line_create_external_table
[2022-12-08T03:30:58.345+0000] {task_command.py:389} INFO - Running <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:30:49.778249+00:00 [running]> on host 8dc4e4d2ec7a
[2022-12-08T03:30:58.476+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=streamify_dag
AIRFLOW_CTX_TASK_ID=wait_in_seller_line_create_external_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T03:30:49.778249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-08T03:30:49.778249+00:00
[2022-12-08T03:30:58.479+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-12-08T03:30:58.480+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-12-08T03:30:58.491+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1592, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 399, in create_empty_table
    table_id=table_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 195, in _resolve_table_reference
    TableReference.from_api_repr(table_resource["tableReference"])
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 279, in from_api_repr
    return cls(DatasetReference(project, dataset_id), table_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/dataset.py", line 260, in __init__
    raise ValueError("Pass a string for project")
ValueError: Pass a string for project
[2022-12-08T03:30:58.507+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=streamify_dag, task_id=wait_in_seller_line_create_external_table, execution_date=20221208T033049, start_date=20221208T033058, end_date=20221208T033058
[2022-12-08T03:30:58.530+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task wait_in_seller_line_create_external_table (Pass a string for project; 157)
[2022-12-08T03:30:58.549+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-08T03:30:58.585+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
